"use client"
import  MyContext  from '@/helper/Context'
import './globals.css'
import Header from '@/Components/Header'



// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Header/>
        <MyContext>
        {children}
        </MyContext>
        
        </body>
    </html>
  )
}
